METHOD_WEIGHTS = {
    "swap": 1.0,
    "supply": 1.0,
    "deposit": 1.0,
    "withdraw": 1.0,
    "redeem": 1.0,
    "borrow": 1.0,
    "repay": 1.0,
    "liquidity": 1.0,
    "stake": 1.0,
    "bridge": 1.0,
    "send": 1.0,
    "multicall": 0.8,
    "execute": 0.8,
    "flashloan": 0.8,
    "claim": 0.8,
    "transfer": 0.5,
    "mint": 0.5,
    "burn": 0.5,
    "sell": 0.5,
    "buy": 0.5,
    "exchange": 0.5,
    "approve": 0.2,
    "permit": 0.2,
}
